language: r
warnings_are_errors: true

r_github_packages:
  - jimhester/covr

env:
  - global:
    - WARNINGS_ARE_ERRORS=1

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change